### Cache 

### schema (JSON)
POST http://localhost:8989/api/v2/cache/schema/tbrelcod
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC


### schema (SQLite)
POST http://localhost:8989/api/v2/cache/schema/tbrelcod/sqlite
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC


### schema (data)
POST http://localhost:8989/api/v2/cache/schema/tbrelcod/data
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC


### status 
POST http://localhost:8989/api/v2/cache/status
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC


### load
POST http://localhost:8989/api/v2/cache/load/tbrelcod
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC


### unload 
POST http://localhost:8989/api/v2/cache/unload/tbrelcod
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC


# 
# REST Client for Visual Studio Code
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
#
